name: SteinerGlobal
favicon: null
layout_spectrum: 0.26557096606120467
typography_spectrum: 0.8603963777422905
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.8357947547920048
  lightness: 0.537588254082948
  saturation: 0.4761930836830288
  rhythmicContrast: 0.405856657307595
purpose: []
